# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: true
          NODE_ENV: production
      - name: Setup package for deploy
        run: cp package-deploy.json package.json
      - name: Push to remote
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          git config --global user.name "github-actions[bot]"	
          git config --global user.email "jeopardy+github-actions[bot]@users.noreply.github.com"	
          rm .gitignore	
          git checkout -b release
          git add --all
          git commit --quiet -m "Built from ${{ github.sha }}" 	
          git push origin release -f
      - name: Push to dokku
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          git remote add dokku dokku@jeopardy.centralus.cloudapp.azure.com:jeopardy
          git push dokku release:master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
